### ISSUE TITLE
transition not working

### ISSUE THREAD

**Issue by bardiarastin** [Coffcer/vue-bootstrap-modal#10]
hi, i'm using this component with bootstrap 4 , transition is not working so the modal appears on the screen immediately . any solution or jsfiddle .... ?
tnx

**Comment by smartapant** [comment]
@bardiarastin the same issue, have you found any solution?

**Comment by bardiarastin** [comment]
@smartapant i gave up on this and used https://vuejs.org/v2/examples/modal.html instead

**Comment by smartapant** [comment]
@bardiarastin and I've made a mix of these two components yesterday, works like a charm :)

**Comment by bardiarastin** [comment]
@smartapant the modal i mentioned before doesn't close while clicking on dark backdrop, i added that feature + some bootstrap 4 styles ;-) . if you have enough time it would be nice if you publish what you made.

**Comment by VladZen** [comment]
@bardiainjast this is because of wrong using of the transition. If you set breakpoint on the root element you'll see transition is running, but VueJS transition is based on css transition-duration and transition property is set for children elements but not the root - so we see transition with 0s duration. [Here](https://github.com/VladZen/vue-bootstrap-modal/blob/master/Modal.vue) is the working example based on Vue2.
